[package]
name = "max_bot"
version = "0.1.0"
authors = ["Aomitsu <52425530+Aomitsu@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.6"
kankyo = "0.2"
log = "0.4"
serenity = "0.8.0"
serde_json = "1.0.40"
reqwest = { version = "0.9.19", default-features = false, features = ["rustls-tls"] }
async-trait = "0.1.26"
base64 = "0.12.0"
rand = "0.7.3"
apiai = "0.1.1"
config = "0.10.1"